import { eanoApi } from "@/services/api/eanoApi"
import type { PaginationMeta } from "@/types/driver"
import type { AdminUser, PageResponse, PrivacyAssessment, PrivacyRequest, PrivacySource, PrivacyStatus, PrivacyType, ProductionReadiness, RoleDefinition } from "@/types/governance"

type Wrapped<T> = { data: T; meta?: PaginationMeta }

export const governanceApi = eanoApi.injectEndpoints({ endpoints: (builder) => ({
  getUsers: builder.query<PageResponse<AdminUser>, { page: number; search?: string }>({ query: (params) => ({ url: "/admin/users", params: { ...params, per_page: 20 } }), transformResponse: (response: Wrapped<AdminUser[]>) => ({ data: response.data, meta: response.meta ?? { current_page: 1, per_page: 20, total: response.data.length, last_page: 1 } }), providesTags: ["Users"] }),
  createAdminUser: builder.mutation<AdminUser, { name: string; email: string; password: string; password_confirmation: string; roles: string[] }>({ query: (body) => ({ url: "/admin/users", method: "POST", body }), transformResponse: (response: Wrapped<AdminUser>) => response.data, invalidatesTags: ["Users"] }),
  setUserActive: builder.mutation<AdminUser, { id: string; active: boolean }>({ query: ({ id, active }) => ({ url: `/admin/users/${id}/${active ? "enable" : "disable"}`, method: "POST" }), transformResponse: (response: Wrapped<AdminUser>) => response.data, invalidatesTags: ["Users", "AuditEvents"] }),
  deleteUser: builder.mutation<{ deleted: true }, { id: string; confirmation: string }>({ query: ({ id, confirmation }) => ({ url: `/admin/users/${id}`, method: "DELETE", body: { confirmation } }), transformResponse: (response: Wrapped<{ deleted: true }>) => response.data, invalidatesTags: ["Users", "AuditEvents"] }),
  getRoles: builder.query<RoleDefinition[], void>({ query: () => "/admin/roles", transformResponse: (response: Wrapped<RoleDefinition[]>) => response.data }),
  getReadiness: builder.query<ProductionReadiness, void>({ query: () => "/admin/readiness", transformResponse: (response: Wrapped<ProductionReadiness>) => response.data, providesTags: ["Readiness"] }),
  getPrivacyRequests: builder.query<PageResponse<PrivacyRequest>, { page: number; type?: PrivacyType; status?: PrivacyStatus; overdue?: boolean }>({ query: (params) => ({ url: "/privacy-requests", params: { ...params, per_page: 20 } }), transformResponse: (response: Wrapped<PrivacyRequest[]>) => ({ data: response.data, meta: response.meta ?? { current_page: 1, per_page: 20, total: response.data.length, last_page: 1 } }), providesTags: ["Privacy"] }),
  getPrivacyRequest: builder.query<PrivacyRequest, string>({ query: (id) => `/privacy-requests/${id}`, transformResponse: (response: Wrapped<PrivacyRequest>) => response.data, providesTags: ["Privacy"] }),
  createPrivacyRequest: builder.mutation<PrivacyRequest, { driver_id: string; type: PrivacyType; received_at: string; due_at: string | null; source: PrivacySource; request_notes: string | null }>({ query: (body) => ({ url: "/privacy-requests", method: "POST", body }), transformResponse: (response: Wrapped<PrivacyRequest>) => response.data, invalidatesTags: ["Privacy", "Dashboard"] }),
  transitionPrivacyRequest: builder.mutation<PrivacyRequest, { id: string; status: PrivacyStatus; reason: string | null; version: number }>({ query: ({ id, ...body }) => ({ url: `/privacy-requests/${id}/transitions`, method: "POST", body }), transformResponse: (response: Wrapped<PrivacyRequest>) => response.data, invalidatesTags: ["Privacy", "Dashboard", "AuditEvents"] }),
  setPrivacyLegalHold: builder.mutation<PrivacyRequest, { id: string; enabled: boolean; reason: string; version: number }>({ query: ({ id, ...body }) => ({ url: `/privacy-requests/${id}/legal-hold`, method: "POST", body }), transformResponse: (response: Wrapped<PrivacyRequest>) => response.data, invalidatesTags: ["Privacy", "Dashboard", "AuditEvents"] }),
  getPrivacyAssessment: builder.query<PrivacyAssessment, string>({ query: (id) => `/privacy-requests/${id}/assessment`, transformResponse: (response: Wrapped<PrivacyAssessment>) => response.data }),
  completePrivacyRequest: builder.mutation<PrivacyRequest, { id: string; completion_reference: string; completion_notes: string | null; version: number }>({ query: ({ id, ...body }) => ({ url: `/privacy-requests/${id}/complete`, method: "POST", body }), transformResponse: (response: Wrapped<PrivacyRequest>) => response.data, invalidatesTags: ["Privacy", "Dashboard", "AuditEvents"] }),
}) })

export const { useGetUsersQuery, useCreateAdminUserMutation, useSetUserActiveMutation, useDeleteUserMutation, useGetRolesQuery, useGetReadinessQuery, useGetPrivacyRequestsQuery, useGetPrivacyRequestQuery, useCreatePrivacyRequestMutation, useTransitionPrivacyRequestMutation, useSetPrivacyLegalHoldMutation, useGetPrivacyAssessmentQuery, useCompletePrivacyRequestMutation } = governanceApi
