import { useState, type FormEvent } from "react"
import { Button, Card, CardContent, CardHeader, CardTitle, Select, Skeleton, Textarea } from "@/components"
import { apiError } from "@/components/auth/apiError"
import { DriverStatusBadge } from "@/components/drivers/DriverStatusBadge"
import { useLanguage } from "@/i18n"
import { useGetDriverStatusHistoryQuery, useTransitionDriverStatusMutation } from "@/services/api/admin/adminApi"
import type { Driver, DriverStatus } from "@/types/driver"
const editableStatuses: DriverStatus[] = ["documents_missing", "under_review", "active", "rejected"]
export function DriverStatusPanel({driver}:{driver:Driver}){const {t}=useLanguage();const history=useGetDriverStatusHistoryQuery(driver.id);const [transition,state]=useTransitionDriverStatusMutation();const [status,setStatus]=useState<DriverStatus|"">("");const [reason,setReason]=useState("");const [message,setMessage]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();if(!status)return;setMessage("");try{await transition({id:driver.id,status,reason:reason||null,version:driver.version}).unwrap();setStatus("");setReason("")}catch(error){setMessage(apiError(error,t("adminTools.status.errors.change")).message)}};return <Card><CardHeader><CardTitle>{t("adminTools.status.title")}</CardTitle></CardHeader><CardContent>{message&&<p className="mb-3 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{message}</p>}<div className="flex items-center gap-2"><span className="text-sm text-muted-foreground">{t("adminTools.status.current")}</span><DriverStatusBadge status={driver.status}/></div><form className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]" onSubmit={e=>void submit(e)}><Select placeholder={t("adminTools.status.choose")} options={editableStatuses.filter(value => value !== driver.status).map(value=>({label:t(`drivers.status.${value}`),value}))} value={status||undefined} onChange={value=>setStatus(value as DriverStatus)}/><Textarea placeholder={t("adminTools.status.reason")}  value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit" disabled={!status||state.isLoading}>{t("adminTools.status.apply")}</Button></form><div className="mt-5 border-t pt-4"><p className="mb-3 font-medium">{t("adminTools.status.history")}</p>{history.isLoading?<Skeleton className="h-20"/>:<div className="space-y-2">{history.data?.map(item=><div key={item.id} className="rounded-md bg-muted/50 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{item.from_status?t(`drivers.status.${item.from_status}`):"—"} → <strong>{t(`drivers.status.${item.to_status}`)}</strong></span><span className="text-muted-foreground">{new Date(item.created_at).toLocaleString()}</span></div>{item.reason&&<p className="mt-1">{item.reason}</p>}<p className="text-xs text-muted-foreground">{item.changed_by?.name??"—"}</p></div>)}</div>}</div></CardContent></Card>}
