import { useMemo, useCallback } from "react"
import { DataTable, type ColumnConfig } from "@/eano/data-table-builder"
import type { CityOption } from "@/types/dashboard"
import { Check, Pencil, Plus, X } from "lucide-react"
import { useState, type FormEvent } from "react"
import { Button, Card, CardContent, Input, Page, PageHeader, Skeleton, } from "@/components"
import { apiError } from "@/components/auth/apiError"
import { useLanguage } from "@/i18n"
import { useCreateCityMutation, useGetAdminCitiesQuery, useSetCityStatusMutation, useUpdateCityMutation } from "@/services/api/admin/adminApi"
export default function CitiesPage(){const {t}=useLanguage();const query=useGetAdminCitiesQuery(true);const [create,cs]=useCreateCityMutation();const [update,us]=useUpdateCityMutation();const [setStatus,ss]=useSetCityStatusMutation();const [name,setName]=useState("");const [edit,setEdit]=useState<{id:string;name:string}|null>(null);const [message,setMessage]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();setMessage("");try{if(edit){await update({id:edit.id,name:edit.name}).unwrap();setEdit(null)}else{await create({name}).unwrap();setName("")}}catch(error){setMessage(apiError(error,t("adminTools.cities.errors.save")).message)}};const toggle=useCallback(async(id:string,is_active:boolean)=>{setMessage("");try{await setStatus({id,is_active:!is_active}).unwrap()}catch(error){setMessage(apiError(error,t("adminTools.cities.errors.status")).message)}},[setStatus,t]);
  const columns = useMemo<ColumnConfig<CityOption>[]>(() => [
    { key: "name", label: t("adminTools.cities.name"), render: (_, city) => (<div className="font-medium">{city.name}</div>) },
    { key: "drivers_count", label: t("adminTools.cities.drivers"), render: (_, city) => (<div>{city.drivers_count}</div>) },
    { key: "is_active", label: t("adminTools.cities.status"), render: (_, city) => (<div>{city.is_active?t("adminTools.cities.active"):t("adminTools.cities.inactive")}</div>) },
    { key: "actions", label: t("adminTools.cities.actions"), render: (_, city) => (<div className="text-end"><Button variant="ghost" size="sm" onClick={()=>setEdit({id:city.id,name:city.name})}><Pencil />{t("adminTools.cities.edit")}</Button><Button variant={city.is_active?"outline":"default"} size="sm" disabled={ss.isLoading} onClick={()=>void toggle(city.id,city.is_active)}>{city.is_active?<X />:<Check />}{city.is_active?t("adminTools.cities.disable"):t("adminTools.cities.enable")}</Button></div>) },
  ], [t, ss.isLoading, toggle])
return <Page><PageHeader title={t("adminTools.cities.title")} subtitle={t("adminTools.cities.subtitle")}/>{message&&<p className="mt-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{message}</p>}<Card className="mt-4"><CardContent className="pt-6"><form className="flex gap-2" onSubmit={e=>void submit(e)}><Input required label={edit?t("adminTools.cities.editName"):t("adminTools.cities.newName")} value={edit?.name??name} onChange={e=>edit?setEdit({...edit,name:e.target.value}):setName(e.target.value)}/><div className="flex items-end gap-2"><Button disabled={cs.isLoading||us.isLoading}><Plus />{edit?t("adminTools.cities.save"):t("adminTools.cities.add")}</Button>{edit&&<Button type="button" variant="outline" onClick={()=>setEdit(null)}><X />{t("adminTools.common.cancel")}</Button>}</div></form></CardContent></Card><Card className="mt-4 overflow-hidden"><CardContent className="p-0">{query.isLoading?<div className="space-y-3 p-5">{[1,2,3].map(i=><Skeleton key={i} className="h-12"/>)}</div>:<DataTable<CityOption> tableId="fleetlery-admin-cities" data={query.data ?? []} columns={columns} rowKey={(city) => city.id} preset="simple" emptyMessage={t("adminTools.cities.empty")} className="rounded-none border-0 shadow-none" />}</CardContent></Card></Page>}
